name: Web application lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: â¬‡ï¸ Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: â¬‡ï¸ Install dependencies
      run: |
        python -m pip install poetry
        poetry install --only dev

    - name: ğŸš¨ Lint
      run: |
        poetry run ruff check web/app
        poetry run mypy web/app/
